AllCops:
  NewCops: enable

  # rubocop 1.13.0+ requires ruby 2.5+
  TargetRubyVersion: 2.5

Layout/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Naming/FileName:
  Exclude:
    - "lib/rubocop-itamae.rb"
    - "rubocop-itamae.gemspec"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
