# AllCops:
#   TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Naming/FileName:
  Exclude:
    - "lib/rubocop-itamae.rb"
    - "rubocop-itamae.gemspec"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
