AllCops:
  NewCops: enable
  SuggestExtensions: false

  # rubocop 1.72.0+ requires ruby 2.7+
  TargetRubyVersion: 2.7

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "rubocop-itamae.gemspec"

Naming/FileName:
  Exclude:
    - "lib/rubocop-itamae.rb"
    - "rubocop-itamae.gemspec"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
