AllCops:
  # rubocop 0.69.0+ requires ruby 2.3+
  TargetRubyVersion: 2.3

Layout/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Naming/FileName:
  Exclude:
    - "lib/rubocop-itamae.rb"
    - "rubocop-itamae.gemspec"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
