Itamae/CdInExecute:
  Description: Check that `cd` in `execute`.
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-itamae/RuboCop/Cop/Itamae/CdInExecute

Itamae/CommandEqualsToName:
  Description: Check that `command` doesn't equals to name of `execute`.
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-itamae/RuboCop/Cop/Itamae/CommandEqualsToName

Itamae/NeedlessDefaultAction:
  Description: Checks whether default action is written for resource.
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-itamae/RuboCop/Cop/Itamae/NeedlessDefaultAction

Itamae/NodeKeyType:
  Description: Check for node key type.
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-itamae/RuboCop/Cop/Itamae/NodeKeyType
  EnforcedStyle: symbol
  SupportedStyles:
    - symbol
    - string

Itamae/RecipePath:
  Description: Checks whether the recipe is placed under `cookbooks` dir or `roles` dir.
  Enabled: true
  StyleGuide: http://www.rubydoc.info/gems/rubocop-itamae/RuboCop/Cop/Itamae/RecipePath
