name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/rubocop-itamae
      gem-name:  rubocop-itamae
    permissions:
      contents: write
      id-token: write
